#!/usr/bin/env bash
# scribe-screen-setup.sh — set up the optional screen-OCR bridge.
#
# Gives the live analyst optional access to on-screen text (a shared slide,
# a doc someone is presenting, etc.) alongside the audio transcript.
#
# Entirely optional and best-effort: if the local tools this needs aren't
# present, this script warns, changes nothing, and exits nonzero — the
# analyst simply keeps running on transcript-only context, which is the
# default and fully supported mode. It never touches audio capture, never
# writes a persistent screen image, and never talks to any meeting app.
#
# Requires, on the machine scribe runs on:
#   - a screenshot tool: one of grim, scrot, import (ImageMagick),
#     gnome-screenshot, or spectacle
#   - tesseract (OCR engine)
#
# On success: writes a small wrapper (scribe-screen-ocr.sh, next to this
# script) that captures one screenshot to a RAM-only temp file, OCRs it to
# stdout as plain text, and deletes the temp file — no screenshot image is
# ever written to persistent disk — then prints the SCRIBE_SCREEN_OCR_CMD
# export line to wire it in.
#
# Usage: scribe-screen-setup.sh
set -uo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
WRAPPER="$HERE/scribe-screen-ocr.sh"

find_screenshot_tool() {
	local tool
	for tool in grim scrot import gnome-screenshot spectacle; do
		if command -v "$tool" >/dev/null 2>&1; then
			echo "$tool"
			return 0
		fi
	done
	return 1
}

if ! command -v tesseract >/dev/null 2>&1; then
	echo "warning: scribe-screen-setup.sh: tesseract (OCR engine) not found; skipping screen-OCR bridge — analyst runs without screen context" >&2
	exit 1
fi

SHOT_TOOL="$(find_screenshot_tool)" || {
	echo "warning: scribe-screen-setup.sh: no screenshot tool found (looked for grim/scrot/import/gnome-screenshot/spectacle); skipping screen-OCR bridge — analyst runs without screen context" >&2
	exit 1
}

case "$SHOT_TOOL" in
	grim)             capture_cmd='grim "$SHOT"' ;;
	scrot)            capture_cmd='scrot -o "$SHOT"' ;;
	import)           capture_cmd='import -window root "$SHOT"' ;;
	gnome-screenshot) capture_cmd='gnome-screenshot -f "$SHOT"' ;;
	spectacle)        capture_cmd='spectacle -b -n -o "$SHOT"' ;;
esac

cat > "$WRAPPER" <<WRAPPEREOF
#!/usr/bin/env bash
# scribe-screen-ocr.sh — generated by scribe-screen-setup.sh. Captures one
# screenshot to a RAM-only temp file, OCRs it to stdout as plain text, then
# deletes the temp file. Never writes a persistent screen image.
set -uo pipefail
SHOT="\$(mktemp "\${SCRIBE_RAMROOT:-/dev/shm}/scribe-screen-XXXXXX.png")"
trap 'rm -f "\$SHOT"' EXIT
$capture_cmd >/dev/null 2>&1
tesseract "\$SHOT" - --psm 6 2>/dev/null
WRAPPEREOF
chmod +x "$WRAPPER"

echo "scribe-screen-setup.sh: screen-OCR bridge ready ($WRAPPER)" >&2
echo "  screenshot tool: $SHOT_TOOL" >&2
echo "  OCR engine:      tesseract" >&2
echo "$WRAPPER"
echo "  add to scribe.conf (or your shell profile):  export SCRIBE_SCREEN_OCR_CMD=\"$WRAPPER\"" >&2
